### ISSUE TITLE
[Bug] Theme toggle doesn't work after the route is changed

### ISSUE THREAD

**Issue by karthickm98** [AREA44/astro-shadcn-ui-template#33]
Description: The dark theme is switching back to light theme whenever the route is changed
steps to reproduce :
1. switch dark theme
2. navigate to another page and comeback the theme is switched back to default theme

**Comment by diomed** [comment]
and I have the opposite issue. my light theme is switching back to dark theme. 🤔

**Comment by diomed** [comment]
> @KarthickM98 can you give me more information on this issue like a repo or a link to a website? [My site](https://astro-shadcn-ui-template.vercel.app) still works well.

your site is basically one page template.
really barebones. should have more pages, and more examples; like cards, tabs and calendar for example

**Comment by diomed** [comment]
> > > @KarthickM98 can you give me more information on this issue like a repo or a link to a website? [My site](https://astro-shadcn-ui-template.vercel.app) still works well.
> > 
> > 
> > your site is basically one page template. really barebones. should have more pages, and more examples; like cards, tabs and calendar for example
> 
> I want to keep my site simple because this helps people easily customize anything that they want. So I don't add more examples.

that's the problem man. 
it's easier to customise by deleting than by adding.
about page wouldnt kill you.
or like demo preview page off couple of components
